parameters:
    my_user_provider.class: Geekhub\UserBundle\UserProvider\FOSUBUserProvider
    abstact_social_network_provider.class: Geekhub\UserBundle\UserProvider\AbstractSocialNetworkProvider
    vkontakte_user_provider.class: Geekhub\UserBundle\UserProvider\VkontakteUserProvider
    facebook_user_provider.class: Geekhub\UserBundle\UserProvider\FacebookUserProvider
    odnoklassniki_user_provider.class: Geekhub\UserBundle\UserProvider\OdnoklassnikiUserProvider
    geekhub.user_bundle.user_manager.class: Geekhub\UserBundle\UserManager

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebookId, vkontakte: vkontakteId, odnoklassniki: odnoklassnikiId}]
        calls:
            - [ setVkontakteProvider, [ @vkontakte_user_provider ] ]
            - [ setFacebookProvider, [ @facebook_user_provider ] ]
            - [ setOdnoklassnikiProvider, [ @odnoklassniki_user_provider ] ]
    abstract_social_network_provider:
        class: "%abstact_social_network_provider.class%"
        arguments: [@fos_user.user_manager]
        calls:
            - [ setKernelWebDir, [ %kernel.root_dir% ] ]

    vkontakte_user_provider:
        class: "%vkontakte_user_provider.class%"
        parent: abstract_social_network_provider
    facebook_user_provider:
        class: "%facebook_user_provider.class%"
        parent: abstract_social_network_provider
    odnoklassniki_user_provider:
        class: "%odnoklassniki_user_provider.class%"
        parent: abstract_social_network_provider
        calls:
            - [setAppKeys, [{odnoklassniki_app_key: %odnoklassniki_app_key%, odnoklassniki_app_secret: %odnoklassniki_app_secret%}]]
    geekhub.user_bundle.user_manager:
        class: "%geekhub.user_bundle.user_manager.class%"

